#!/bin/bash

endpointFile="/tmp/endpoint"
speedResult="/tmp/speedresult"
sortResult="/tmp/sortresult"


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

if [ -f $endpointFile ] ; then 
       rm $endpointFile
fi

if [ -f $speedResult ] ; then
	rm $speedResult
fi

if [ -f $sortResult ] ; then 
	rm $sortResult
fi


cd /etc/wireguard/


echo "[+] Creating Endpoint List"
grep -Ri "Endpoint" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | uniq > $endpointFile


echo "[+] Starting Test"
while read i; do
      	serverName=$(grep -lRioE "$i")
	pingTest=$(ping -c 4 -i 0.2 "$i" | tail -1 | awk '{print $4}' | cut -d '/' -f 2)    
	echo "$serverName $pingTest" >> $speedResult
done < $endpointFile
rm $endpointFile

echo "[+] Sorting Server"
sort -h -k2 $speedResult >> $sortResult 
rm $speedResult
fastestServer=$(grep -m1 "" $sortResult |  awk '{print $1;}' | cut -f1 -d".")
echo "[+] Fastest server is $fastestServer"
read -p "Do you want to establish a Wireguard connexion to $fastestServer (y/n)?" choice
case "$choice" in
  y|Y ) wg-quick up $fastestServer&;;
  n|N ) exit;;
  * ) echo "invalid";;
esac
rm $sortResult

